package ptclenforcer

import (
	"school/project/simplelib"
) 

// Autogenerated Typestate API

type S00 struct {
	Prtcl *simplelib.SimpleStruct
	finalState *bool
	used bool
}

type E00 struct {
	Prtcl *simplelib.SimpleStruct
	finalState *bool
	used bool
}

type E00Checker struct {
	finalState *bool
}

func (f *E00Checker) FinalizeChecker() func() {
	return func() {
		if f.finalState == nil || !*f.finalState {
			panic("Final state was not reached")
		}
	}
}

func NewS00(prtcl ...*simplelib.SimpleStruct) (*S00, *E00Checker) {
	finalReached := false
	checker := &E00Checker{finalState: &finalReached}
	var p *simplelib.SimpleStruct
	if len(prtcl) > 0 && prtcl[0] != nil {
		p = prtcl[0]
	} else {
		p = &simplelib.SimpleStruct{}
	}
	return &S00{
		Prtcl: p,
		finalState: &finalReached,
		used: false,
	}, checker
}

// S00 - M01 -> E00
func (x *S00) M01() (E00, string) {
	if x.used {
		panic("S00 has been used")
	}
	x.used = true
	res0 := x.Prtcl.M1()
	*x.finalState = true
	return E00{Prtcl: x.Prtcl, finalState: x.finalState, used: false}, res0
}

